language: node_js

node_js:
  # node latest stable Node.js release
  - node
  # lts/* latest LTS Node.js release
  #- 'lts/*'

cache:
  directories:
    - node_modules

branches:
  only:
    - main

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn install

before_deploy:
  - npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN

deploy:
  provider: script
  script: npx lerna publish -y from-git
  skip_cleanup: true
  on:
    tags: true
# notifications:
#   email: false
#   slack:
#     rooms:
#       - glriaroom:$SLACK_TOKEN#devops
#     on_success: change # default : always
#     on_failure: always # default : always
